namespace DdiCodeGen.Generator;

public sealed class CodeGenerator
{
    private readonly ITemplateStore _templateStore;

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeGenerator"/> class.
    /// </summary>
    /// <param name="templateStore">Template store providing Handlebars templates.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="templateStore"/> is null.</exception>
    public CodeGenerator(ITemplateStore templateStore)
    {
        _templateStore = templateStore ?? throw new ArgumentNullException(nameof(templateStore));
    }

    /// <summary>
    /// Generates all code files for the given canonical model.
    /// </summary>
    /// <param name="model">Canonical model DTO containing registry and instance definitions.</param>
    /// <returns>A dictionary of file names mapped to generated file content.</returns>
    public IReadOnlyDictionary<string, string> GenerateFiles(CanonicalModelDto model)
    {
        var files = new Dictionary<string, string>();

        // Build expandos once
        var expandos = ExpandoPipeline.ToExpandoList(model);

        // Emit aggregate registry + accessors
        EmitRegistry(files, model, expandos);
        EmitAccessors(files, model);

        // Emit per-instance fragments
        foreach (var expando in expandos)
        {
            EmitInstanceFragments(files, model, expando);
        }

        return files;
    }

    /// <summary>
    /// Emits the aggregate registry file.
    /// </summary>
    private void EmitRegistry(
        IDictionary<string, string> files,
        CanonicalModelDto model,
        List<ExpandoObject> expandos)
    {
        var registryTemplate = Handlebars.Compile(_templateStore.GetTemplate("Registry"));

        var registryContext = new Dictionary<string, object?>
        {
            ["GeneratedNamespace"] = model.CodeGen.NamespaceName,
            ["RegistryClassName"] = model.CodeGen.RegistryClassName,
            ["GeneratedHeader"] = $"// Auto-generated by DdiCodeGen ({DateTime.UtcNow:o})",
            ["Instances"] = expandos
        };

        EmitFile(files, model.CodeGen.GeneratedCodePath, "Registry.cs", registryTemplate(registryContext));
    }

    /// <summary>
    /// Emits the registry accessors file.
    /// </summary>
    private void EmitAccessors(
        IDictionary<string, string> files,
        CanonicalModelDto model)
    {
        var accessorTemplate = Handlebars.Compile(_templateStore.GetTemplate("Registry.Accessors"));
        var accessorContext = ExpandoPipeline.DeriveAccessorTokens(model);

        EmitFile(files, model.CodeGen.GeneratedCodePath, "Registry.Accessors.cs", accessorTemplate(accessorContext));
    }

    /// <summary>
    /// Emits per-instance fragments (member, elements initializer, assignments initializer).
    /// </summary>
private void EmitInstanceFragments(
    IDictionary<string, string> files,
    CanonicalModelDto model,
    IDictionary<string, object?> expando)
{
    var niName = (string)expando["NamedInstanceName"]!;

    // Registry.InstanceField (backing field declaration)
    var fieldTemplate = Handlebars.Compile(_templateStore.GetTemplate("Registry.InstanceField"));
    EmitFile(files, model.CodeGen.GeneratedCodePath, $"{niName}_InstanceField.cs", fieldTemplate(expando));

    // Registry.InstanceFactory (creation logic)
    var factoryTemplate = Handlebars.Compile(_templateStore.GetTemplate("Registry.InstanceFactory"));
    EmitFile(files, model.CodeGen.GeneratedCodePath, $"{niName}_InstanceFactory.cs", factoryTemplate(expando));

    // Elements initializer if Elements present
    if (expando.TryGetValue("Elements", out var elementsObj) &&
        elementsObj is List<Dictionary<string, object?>> elements &&
        elements.Count > 0)
    {
        var elementsInitializerTemplate = Handlebars.Compile(_templateStore.GetTemplate("Elements.Initializer"));
        EmitFile(files, model.CodeGen.GeneratedCodePath, $"{niName}_ElementsInitializer.cs", elementsInitializerTemplate(expando));
    }

    // Assignments initializer if Assignments present
    if (expando.TryGetValue("Assignments", out var assignmentsObj) &&
        assignmentsObj is List<Dictionary<string, object?>> assignments &&
        assignments.Count > 0)
    {
        var assignmentsInitializerTemplate = Handlebars.Compile(_templateStore.GetTemplate("Assignments.Initializer"));
        EmitFile(files, model.CodeGen.GeneratedCodePath, $"{niName}_Initializer.cs", assignmentsInitializerTemplate(expando));
    }
}


    /// <summary>
    /// Emits a generated file with provenance header.
    /// </summary>
    private static void EmitFile(
        IDictionary<string, string> files,
        string generatedCodePath,
        string fileName,
        string content)
    {
        var fullContent = BuildProvenanceHeader(generatedCodePath) + content;
        files[fileName] = fullContent;
    }

    /// <summary>
    /// Builds a provenance header for generated files.
    /// </summary>
    private static string BuildProvenanceHeader(string generatedCodePath)
    {
        return $"// Generated by DdiCodeGen at {DateTime.UtcNow:o}\n" +
               $"// Output Path: {generatedCodePath}\n";
    }
}
